#!/bin/bash

grunt swatch:cosmo

# See http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html
aws s3 sync . s3://${AWS_BUCKET}/${1} --cache-control max-age=604800 --acl public-read \
    --exclude "*" \
    --include "docs/index.html" \
    --include "docs/_assets/*" \
    --include "docs/_vendor/*" \
    --include "docs/cosmo/*" \
    --include "docs/4/cosmo/*" \
    --include "dist/cosmo/*"
